Air polution app
mhnazary/react-capstone-project pull request #4
Opened 2023-09-05 20:32 UTC by mhnazary

In this project I did:

- [ ] Stunk, CRA, Jest-redux, router, redux, react-icons

- [ ] Create a components folder with:

File air pollution items and a List of these items for the detail section of the page that fetch data from https://openweathermap.org/api/air-pollution

- [ ] File countries items and a list of these items for the home page
- [ ] Europe countries for the API of air pollution parameters
- [ ] Navbar for the navigation bar of the web app using router
- [ ] Search bar on the home page to filter country
- [ ] Back button function in the navbar to return to the home page
- [ ] Detail button in each country to see the air pollution data of that country (Only available in the arrow button, not the entire section)
- [ ] Redux store and DetailSlice for API fetch and search reducers.
- [ ] Jest test for AirItem.js, CountriesList.js, CountriesItem.js and DetailSlice.js
- [ ] Graph bar for the values of air in the country details section.
- [ ] Linter fix
- [ ] Update readme info and deploy/loom video

2023-09-05 21:39 UTC, Shedrack-Sunday requested changes
Hello @mhnazary          👋 

# CHANGES REQUIRED ♻️

Impressive work on the project so far👏
You've done extremely well so far in this project,  However, there are some adjustments you need to make to move to the next project. 💯

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights   
- Good use of GitHub features ✔️   
- Nice work with the React features ✔️
- Good choice of API and color set ✔️ 
    
    
### Confirmed query:
![image](https://github.com/mhnazary/react-capstone-project/assets/50990925/bf3cf3e3-86df-43cc-afc1-43580fb09ab2)

# Required Changes  🌵  

- [ ] You've done well, However, kindly check some key points notes I pointed out to meet the requirements before moving to the next project 👍 

_Check the comments for a detailed review 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing really improves your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-09-05 21:39 UTC, Shedrack-Sunday commented on src/Test/CountryItem.test.js
> +  const tree = component.toJSON();
- [  ] You did a great job, however, I'm not able to run all your tests successfully. Kindly take a look at the prompt and refactor appropriately 👍 

### View:
![image](https://github.com/mhnazary/react-capstone-project/assets/50990925/cb648586-712d-4427-ad0f-eb44812b4a0e)

2023-09-05 21:57 UTC, mhnazary commented on src/Test/CountryItem.test.js
> +  const tree = component.toJSON();
@Shedrack-Sunday  Thank you for dedicating your valuable time to thoroughly and patiently reviewing my project.
 but, upon executing the test, all the tests passed successfully.

<img width="947" alt="test" src="https://github.com/mhnazary/react-capstone-project/assets/77242944/2a6abc10-118d-4fa6-a79e-76edd22d8ed1">

2023-09-05 22:47 UTC, TadesseDev requested changes
### Hi @mhnazary 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![199733072-bdacca19-8df9-43a7-be93-3aff2f1c15c8](https://user-images.githubusercontent.com/69077061/204107907-c2532abb-b23d-4fda-88f0-1ec9c7b71971.gif)

 ## Highlights
 - [x] You are almost done 🙏


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- N/A


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-05 22:47 UTC, TadesseDev commented on src/components/CountryItem.jsx
> +};
- [ ] Dear @mhnazary, Just as the previous reviewer mentioned, one of the tests is falling. and the issue is you have not passed the required properties to the test data parameter. As you can see here `country, capital, longitude, latitude, image` are required fields, but in your test, you only pass `latitude: 20, longitude: 10`. Please add the remaining properties to the test component and your test will be fine.

![Screen Shot 2023-09-06 at 1 34 22 AM](https://github.com/mhnazary/react-capstone-project/assets/69077061/03224245-528c-4713-b3a9-de524411a0ab)

2023-09-06 06:08 UTC, bienvenuushindi approved these changes
## Status: Approved :heavy_check_mark: :heavy_check_mark:

Hi @mhnazary     

Your project is complete! Great job for making all the required changes 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- Validations correctly implemented
- No linter errors
- All the tests are passing :heavy_check_mark: 
<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-06 06:10 UTC, merged